#!/bin/bash

#################################################
#						#
#		NS-Toolkit			#
#						#
#	Author: Alexander Nordbø		#
#	Mail: alexander@nordsec.no		#
#						#
#	Date: 27.02.2016			#
#						#
#	https://www.github.com/nordsec		#
#################################################

function header {
cat << "EOF"
#    _   _  _____   _______          _ _    _ _
#   | \ | |/ ____| |__   __|        | | |  (_) |
#   |  \| | (___      | | ___   ___ | | | ___| |_
#   | . ` |\___ \     | |/ _ \ / _ \| | |/ / | __|
#   | |\  |____) |    | | (_) | (_) | |   <| | |_
#   |_| \_|_____/     |_|\___/ \___/|_|_|\_\_|\__|
#
#               Welcome To NordSec Toolkit!
#
#       - This is a Really handy script to merge multiple
#         blacklists cross multiple servers for fail2ban or any other firewall.
#
#       - Its also possible to make a complete backup of Mysql.
#
#       Created by Alexander Nordbø on the 23.02.2016
#                       Visit us at
#               https://www.hackingdefinedexperts.com
#               https://github.com/nordsec/NS-Toolkit
EOF
}

function mainmen {
header
echo
  OPTIONS="Synch-Firewall Database-Backup Settings Update Help Quit"
select opt in $OPTIONS; do

        if [ "$opt" = "Database-Backup" ]; then
	mysqlbackup

	elif [ "$opt" = "Synch-Firewall" ]; then
	fsynch

	elif [ "$opt" = "Settings" ]; then
	clear	
	submen

	elif [ "$opt" = "Update" ]; then
	kitupdate

	elif [ "$opt" = "Help" ]; then
	echo "Visit: https://github.com/nordsec/NS-Toolkit"
	cat README.md
	elif [ "$opt" = "Quit" ]; then
	exit
	else

	echo "Bad option"

fi
done
}

function submen {
	header	
	OPTIONS2="Edit-Config Back"
	select opt in $OPTIONS2; do
if [ "$opt" = "Edit-Config" ]; then
	nano config_file
fi
if [ "$opt" = "Back" ]; then
	mainmen
fi

done
}

function srvconfig {

conf="config_file"

if [ -f "$conf" ]; then
read -r -p "config_file exist, do you want to overwrite? (yes/no)" ans
fi

if [ "$ans" = "yes" ]; then
rm config_file
fi

echo "NS-Toolkit Need a config file for it to work"

read -p " Run Config? (yes/no)?" CONT
if [ "$CONT" == "yes" ]; then
  echo "Creating config file, please wait...";
sleep 1

#id=1; You can use server ID if you like.

# Server 1
read -p " Whats the Server1 Hostname or IP?   :" server1;
read -p " Whats the Server1 Username?   :" username1;
read -p " Write the full dir to list (/etc/fail2ban/blacklist)   :" blocklist1;

# Server 2
read -p " Whats the Server2 Hostname or IP?   :" server2;
read -p " Whats the Server2 Username?   :" username2;
read -p " Write the full dir to list (/etc/fail2ban/blacklist)   :" blocklist2;
#read -p " Optional Directory on server2   :" opdir2;

# Mysql
read -p " Whats the Mysql's Hostname?   :" mysqlsrv;
read -p " What is the username for Mysql?   :" mysqluser;
read -p " Tell Mysql where to store backups of the database   :" backupdir;
echo "Good job!, Now give us a seck while we build the config and send you of to the toolbox"
sleep 3

#printf '# This is the configuration file for NS-Toolkit. Feel free to edit manually' > config_file
printf '%s\n' "server1${id}=${server1}" "username1${id}=${username1}" "blocklist1${id}=${blocklist1}" '' >> config_file
printf '%s\n' "server2${id}=${server2}" "username2${id}=${username2}" "blocklist2${id}=${blocklist2}" '' >> config_file
printf '%s\n' "mysqlsrv${id}=${mysqlsrv}" "mysqluser${id}=${mysqluser}" "backupdir${id}=${backupdir}" '' >> config_file

echo "Configuration completed succsessfully! Press [Enter] to continue"; read -r
clear;
mainmen
else
  echo "Press [Enter] to continue to menu"; read -r
clear;
mainmen
fi
}

function reconfig {
	rm /usr/share/NS-Toolkit/config_file
	srvconfig
}

function kitupdate {
	echo "Upating NS-Toolkit, please wait..."
	cd /tmp/
	git clone https://github.com/nordsec/NS-Toolkit.git

	rm /usr/share/NS-Toolkit/README.md
	rm /usr/share/NS-Toolkit/NS-Toolkit.sh
	rm /usr/share/NS-Toolkit/LICENSE
	rm /usr/share/NS-Toolkit/functions

	mv /tmp/NS-Toolkit/* /usr/share/NS-Toolkit/
	chmod +x NS-Toolkit.sh
	chmod +x uninstall.sh
}

function nsinst {
	cd /usr/share/
	echo -n "Downloading Toolbox,"; sleep 1; echo " Adding a Hammer,"; sleep 1; echo "screw driver and a cat?"
	git clone https://github.com/nordsec/NS-Toolkit.git
	cd NS-Toolkit/
	chmod +x NS-Toolkit.sh
	chmod +x uninstall.sh	

	echo "Creating shortcut"

	echo -e '#!/bin/bash' > /usr/bin/nstoolkit
	echo -e 'cd /usr/share/NS-Toolkit && ./NS-Toolkit.sh' >> /usr/bin/nstoolkit
	chmod +x /usr/bin/nstoolkit
	
	echo 'TOS="OK"' >> functions
	clear
	echo "found a blue cat, rm removed it, no worries"
	sleep 3
	clear
	echo "Setup Finished seccessfully! type: nstoolkit to start"

}

function fsynch {
	echo "Synching Firewall Now"
	echo "Copying blocklist from server 1"
# Move the list of blocked ip's from server 1 to server 2#
	scp $blocklist1 $username2'@'$server2:/tmp/ip.blocklist.list1

	echo "merging the blocklists"
#Now ssh in to server 2 and add blocked ip from server 1 the to blocklist on server 2#
	ssh $username2'@'$server2 "
		mv $blocklist2 /tmp/ip.blocklist.list2
		cat /tmp/ip.blocklist.list1 /tmp/ip.blocklist.list2 > $blocklist2
	echo "Cleaning up"
		rm /tmp/ip.*
	echo "restarting services"
		sudo /etc/init.d/fail2ban restart "
sleep 3
	echo "Running the list back to server #1"
# Now we send the full list back to server 1 again#
	ssh $username2'@'$server2 "
sleep 2; echo "Connecting to server, please wait..."
	scp $blocklist2 $username1'@'$server1:/tmp/ip.blocklist.list2 "

# And merge the file again #
		mv $blocklist1 /tmp/ip.blocklist.list1
		cat /tmp/ip.blocklist.list1 /tmp/ip.blocklist.list2 > /tmp/sort.list
	echo "Removing Duplicates from Blacklist1"
		awk '!a[$0]++' /tmp/sort.list >	$blocklist1
	echo "Cleaning up files NOW"
		rm /tmp/ip.* /tmp/sort.list
		sudo /etc/init.d/fail2ban restart
}

function mysqlbackup {
	mysqldump --user=$mysqluser -p --host=$mysqlsrv --all-databases > $backupdir"dump-$( date '+%Y-%m-%d_%H-%M-%S' ).sql"
}
